export { Doctors } from "./doctors/index"
export { CreateDoctor } from "./doctors/create"
export { EditDoctor } from "./doctors/edit"
export { DoctorDetails } from "./doctors/details"
export { AssignClinics } from "./doctors/assign-clinics"
export { ManageSchedule } from "./doctors/schedule"
export { ReviewDoctors } from "./doctors/review"
