export { Patients } from "./patients/index"
export { CreatePatient } from "./patients/create"
export { EditPatient } from "./patients/edit"
export { PatientDetails } from "./patients/details"
export { UploadDocument } from "./patients/upload-document"
